"""Pydantic schemas for request/response validation."""

from app.schemas.datasets import Dataset, DatasetCreate, DatasetUpdate
from app.schemas.analysis import (
    AnalysisRequest,
    DescriptiveRequest,
    DescriptiveResult,
    RegressionRequest,
    RegressionResult,
    PCARequest,
    PCAResult,
    ClassificationRequest,
    ClassificationResult,
    ClusteringRequest,
    ClusteringResult,
)
from app.schemas.common import PaginationParams, PaginatedResponse, ErrorResponse
from app.schemas.user import (
    UserCreate,
    User,
    UserUpdate,
    Token,
    LoginRequest,
    Subscription,
    SubscriptionPlan,
    SubscriptionQuota,
    AnalyticsEventCreate,
    AnalyticsSummary,
    ConsentStatus,
    ConsentUpdate,
    FeedbackCreate,
    Feedback,
)

__all__ = [
    "Dataset",
    "DatasetCreate",
    "DatasetUpdate",
    "AnalysisRequest",
    "DescriptiveRequest",
    "DescriptiveResult",
    "RegressionRequest",
    "RegressionResult",
    "PCARequest",
    "PCAResult",
    "ClassificationRequest",
    "ClassificationResult",
    "ClusteringRequest",
    "ClusteringResult",
    "PaginationParams",
    "PaginatedResponse",
    "ErrorResponse",
    "UserCreate",
    "User",
    "UserUpdate",
    "Token",
    "LoginRequest",
    "Subscription",
    "SubscriptionPlan",
    "SubscriptionQuota",
    "AnalyticsEventCreate",
    "AnalyticsSummary",
    "ConsentStatus",
    "ConsentUpdate",
    "FeedbackCreate",
    "Feedback",
]
